// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stock messages
type StockItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItemRequest) Reset() {
	*x = StockItemRequest{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItemRequest) ProtoMessage() {}

func (x *StockItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItemRequest.ProtoReflect.Descriptor instead.
func (*StockItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *StockItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *StockItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckStockAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItemRequest    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockAvailabilityRequest) Reset() {
	*x = CheckStockAvailabilityRequest{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockAvailabilityRequest) ProtoMessage() {}

func (x *CheckStockAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckStockAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CheckStockAvailabilityRequest) GetItems() []*StockItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type UnavailableItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ItemId            string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName          string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	RequestedQuantity int32                  `protobuf:"varint,3,opt,name=requested_quantity,json=requestedQuantity,proto3" json:"requested_quantity,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,4,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnavailableItem) Reset() {
	*x = UnavailableItem{}
	mi := &file_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnavailableItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnavailableItem) ProtoMessage() {}

func (x *UnavailableItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnavailableItem.ProtoReflect.Descriptor instead.
func (*UnavailableItem) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *UnavailableItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UnavailableItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *UnavailableItem) GetRequestedQuantity() int32 {
	if x != nil {
		return x.RequestedQuantity
	}
	return 0
}

func (x *UnavailableItem) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

type CheckStockAvailabilityResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Available        bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	UnavailableItems []*UnavailableItem     `protobuf:"bytes,2,rep,name=unavailable_items,json=unavailableItems,proto3" json:"unavailable_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckStockAvailabilityResponse) Reset() {
	*x = CheckStockAvailabilityResponse{}
	mi := &file_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockAvailabilityResponse) ProtoMessage() {}

func (x *CheckStockAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckStockAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *CheckStockAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckStockAvailabilityResponse) GetUnavailableItems() []*UnavailableItem {
	if x != nil {
		return x.UnavailableItems
	}
	return nil
}

type UpdateStockRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Items           []*StockItemRequest    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TransactionType string                 `protobuf:"bytes,2,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // 'purchase', 'sales', 'return', 'adjustment', 'allocation'
	ReferenceType   string                 `protobuf:"bytes,3,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`       // 'sales_order', 'invoice', 'work_order', 'return'
	ReferenceId     string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Notes           string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStockRequest) GetItems() []*StockItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UpdateStockRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *UpdateStockRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *UpdateStockRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *UpdateStockRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\x0fserviceandparts\"G\n" +
	"\x10StockItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"X\n" +
	"\x1dCheckStockAvailabilityRequest\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.serviceandparts.StockItemRequestR\x05items\"\xa5\x01\n" +
	"\x0fUnavailableItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12-\n" +
	"\x12requested_quantity\x18\x03 \x01(\x05R\x11requestedQuantity\x12-\n" +
	"\x12available_quantity\x18\x04 \x01(\x05R\x11availableQuantity\"\x8d\x01\n" +
	"\x1eCheckStockAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12M\n" +
	"\x11unavailable_items\x18\x02 \x03(\v2 .serviceandparts.UnavailableItemR\x10unavailableItems\"\xd8\x01\n" +
	"\x12UpdateStockRequest\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.serviceandparts.StockItemRequestR\x05items\x12)\n" +
	"\x10transaction_type\x18\x02 \x01(\tR\x0ftransactionType\x12%\n" +
	"\x0ereference_type\x18\x03 \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"I\n" +
	"\x13UpdateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xed\x01\n" +
	"\x16ServiceAndPartsService\x12y\n" +
	"\x16CheckStockAvailability\x12..serviceandparts.CheckStockAvailabilityRequest\x1a/.serviceandparts.CheckStockAvailabilityResponse\x12X\n" +
	"\vUpdateStock\x12#.serviceandparts.UpdateStockRequest\x1a$.serviceandparts.UpdateStockResponseB\x1bZ\x19erp-billing-service/protob\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_inventory_proto_goTypes = []any{
	(*StockItemRequest)(nil),               // 0: serviceandparts.StockItemRequest
	(*CheckStockAvailabilityRequest)(nil),  // 1: serviceandparts.CheckStockAvailabilityRequest
	(*UnavailableItem)(nil),                // 2: serviceandparts.UnavailableItem
	(*CheckStockAvailabilityResponse)(nil), // 3: serviceandparts.CheckStockAvailabilityResponse
	(*UpdateStockRequest)(nil),             // 4: serviceandparts.UpdateStockRequest
	(*UpdateStockResponse)(nil),            // 5: serviceandparts.UpdateStockResponse
}
var file_proto_inventory_proto_depIdxs = []int32{
	0, // 0: serviceandparts.CheckStockAvailabilityRequest.items:type_name -> serviceandparts.StockItemRequest
	2, // 1: serviceandparts.CheckStockAvailabilityResponse.unavailable_items:type_name -> serviceandparts.UnavailableItem
	0, // 2: serviceandparts.UpdateStockRequest.items:type_name -> serviceandparts.StockItemRequest
	1, // 3: serviceandparts.ServiceAndPartsService.CheckStockAvailability:input_type -> serviceandparts.CheckStockAvailabilityRequest
	4, // 4: serviceandparts.ServiceAndPartsService.UpdateStock:input_type -> serviceandparts.UpdateStockRequest
	3, // 5: serviceandparts.ServiceAndPartsService.CheckStockAvailability:output_type -> serviceandparts.CheckStockAvailabilityResponse
	5, // 6: serviceandparts.ServiceAndPartsService.UpdateStock:output_type -> serviceandparts.UpdateStockResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
