// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: proto/inventory.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceAndPartsService_CheckStockAvailability_FullMethodName = "/serviceandparts.ServiceAndPartsService/CheckStockAvailability"
	ServiceAndPartsService_UpdateStock_FullMethodName            = "/serviceandparts.ServiceAndPartsService/UpdateStock"
)

// ServiceAndPartsServiceClient is the client API for ServiceAndPartsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceAndPartsServiceClient interface {
	CheckStockAvailability(ctx context.Context, in *CheckStockAvailabilityRequest, opts ...grpc.CallOption) (*CheckStockAvailabilityResponse, error)
	UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error)
}

type serviceAndPartsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceAndPartsServiceClient(cc grpc.ClientConnInterface) ServiceAndPartsServiceClient {
	return &serviceAndPartsServiceClient{cc}
}

func (c *serviceAndPartsServiceClient) CheckStockAvailability(ctx context.Context, in *CheckStockAvailabilityRequest, opts ...grpc.CallOption) (*CheckStockAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStockAvailabilityResponse)
	err := c.cc.Invoke(ctx, ServiceAndPartsService_CheckStockAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAndPartsServiceClient) UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStockResponse)
	err := c.cc.Invoke(ctx, ServiceAndPartsService_UpdateStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceAndPartsServiceServer is the server API for ServiceAndPartsService service.
// All implementations must embed UnimplementedServiceAndPartsServiceServer
// for forward compatibility.
type ServiceAndPartsServiceServer interface {
	CheckStockAvailability(context.Context, *CheckStockAvailabilityRequest) (*CheckStockAvailabilityResponse, error)
	UpdateStock(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error)
	mustEmbedUnimplementedServiceAndPartsServiceServer()
}

// UnimplementedServiceAndPartsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceAndPartsServiceServer struct{}

func (UnimplementedServiceAndPartsServiceServer) CheckStockAvailability(context.Context, *CheckStockAvailabilityRequest) (*CheckStockAvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckStockAvailability not implemented")
}
func (UnimplementedServiceAndPartsServiceServer) UpdateStock(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStock not implemented")
}
func (UnimplementedServiceAndPartsServiceServer) mustEmbedUnimplementedServiceAndPartsServiceServer() {
}
func (UnimplementedServiceAndPartsServiceServer) testEmbeddedByValue() {}

// UnsafeServiceAndPartsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceAndPartsServiceServer will
// result in compilation errors.
type UnsafeServiceAndPartsServiceServer interface {
	mustEmbedUnimplementedServiceAndPartsServiceServer()
}

func RegisterServiceAndPartsServiceServer(s grpc.ServiceRegistrar, srv ServiceAndPartsServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceAndPartsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceAndPartsService_ServiceDesc, srv)
}

func _ServiceAndPartsService_CheckStockAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStockAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAndPartsServiceServer).CheckStockAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAndPartsService_CheckStockAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAndPartsServiceServer).CheckStockAvailability(ctx, req.(*CheckStockAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAndPartsService_UpdateStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAndPartsServiceServer).UpdateStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAndPartsService_UpdateStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAndPartsServiceServer).UpdateStock(ctx, req.(*UpdateStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceAndPartsService_ServiceDesc is the grpc.ServiceDesc for ServiceAndPartsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceAndPartsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviceandparts.ServiceAndPartsService",
	HandlerType: (*ServiceAndPartsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStockAvailability",
			Handler:    _ServiceAndPartsService_CheckStockAvailability_Handler,
		},
		{
			MethodName: "UpdateStock",
			Handler:    _ServiceAndPartsService_UpdateStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory.proto",
}
