// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/example.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExampleRequest) Reset() {
	*x = CreateExampleRequest{}
	mi := &file_proto_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExampleRequest) ProtoMessage() {}

func (x *CreateExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExampleRequest.ProtoReflect.Descriptor instead.
func (*CreateExampleRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExampleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExampleResponse) Reset() {
	*x = CreateExampleResponse{}
	mi := &file_proto_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExampleResponse) ProtoMessage() {}

func (x *CreateExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExampleResponse.ProtoReflect.Descriptor instead.
func (*CreateExampleResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExampleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateExampleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExampleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateExampleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateExampleResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExampleRequest) Reset() {
	*x = GetExampleRequest{}
	mi := &file_proto_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleRequest) ProtoMessage() {}

func (x *GetExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleRequest.ProtoReflect.Descriptor instead.
func (*GetExampleRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{2}
}

func (x *GetExampleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExampleResponse) Reset() {
	*x = GetExampleResponse{}
	mi := &file_proto_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleResponse) ProtoMessage() {}

func (x *GetExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleResponse.ProtoReflect.Descriptor instead.
func (*GetExampleResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{3}
}

func (x *GetExampleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetExampleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetExampleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetExampleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetExampleResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListExamplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExamplesRequest) Reset() {
	*x = ListExamplesRequest{}
	mi := &file_proto_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExamplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExamplesRequest) ProtoMessage() {}

func (x *ListExamplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExamplesRequest.ProtoReflect.Descriptor instead.
func (*ListExamplesRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{4}
}

type ListExamplesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Examples      []*ExampleResponse     `protobuf:"bytes,1,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExamplesResponse) Reset() {
	*x = ListExamplesResponse{}
	mi := &file_proto_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExamplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExamplesResponse) ProtoMessage() {}

func (x *ListExamplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExamplesResponse.ProtoReflect.Descriptor instead.
func (*ListExamplesResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{5}
}

func (x *ListExamplesResponse) GetExamples() []*ExampleResponse {
	if x != nil {
		return x.Examples
	}
	return nil
}

type ExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	mi := &file_proto_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{6}
}

func (x *ExampleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExampleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExampleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExampleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ExampleResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpdateExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExampleRequest) Reset() {
	*x = UpdateExampleRequest{}
	mi := &file_proto_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExampleRequest) ProtoMessage() {}

func (x *UpdateExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExampleRequest.ProtoReflect.Descriptor instead.
func (*UpdateExampleRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateExampleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateExampleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateExampleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExampleResponse) Reset() {
	*x = UpdateExampleResponse{}
	mi := &file_proto_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExampleResponse) ProtoMessage() {}

func (x *UpdateExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExampleResponse.ProtoReflect.Descriptor instead.
func (*UpdateExampleResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateExampleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateExampleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateExampleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateExampleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UpdateExampleResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeleteExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExampleRequest) Reset() {
	*x = DeleteExampleRequest{}
	mi := &file_proto_example_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExampleRequest) ProtoMessage() {}

func (x *DeleteExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExampleRequest.ProtoReflect.Descriptor instead.
func (*DeleteExampleRequest) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteExampleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExampleResponse) Reset() {
	*x = DeleteExampleResponse{}
	mi := &file_proto_example_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExampleResponse) ProtoMessage() {}

func (x *DeleteExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_example_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExampleResponse.ProtoReflect.Descriptor instead.
func (*DeleteExampleResponse) Descriptor() ([]byte, []int) {
	return file_proto_example_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteExampleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteExampleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_example_proto protoreflect.FileDescriptor

const file_proto_example_proto_rawDesc = "" +
	"\n" +
	"\x13proto/example.proto\x12\aexample\x1a\x1cgoogle/api/annotations.proto\"*\n" +
	"\x14CreateExampleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x91\x01\n" +
	"\x15CreateExampleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"#\n" +
	"\x11GetExampleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x01\n" +
	"\x12GetExampleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\x15\n" +
	"\x13ListExamplesRequest\"L\n" +
	"\x14ListExamplesResponse\x124\n" +
	"\bexamples\x18\x01 \x03(\v2\x18.example.ExampleResponseR\bexamples\"\x8b\x01\n" +
	"\x0fExampleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"R\n" +
	"\x14UpdateExampleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x91\x01\n" +
	"\x15UpdateExampleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"&\n" +
	"\x14DeleteExampleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x15DeleteExampleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xab\x04\n" +
	"\x0eExampleService\x12k\n" +
	"\rCreateExample\x12\x1d.example.CreateExampleRequest\x1a\x1e.example.CreateExampleResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/examples\x12d\n" +
	"\n" +
	"GetExample\x12\x1a.example.GetExampleRequest\x1a\x1b.example.GetExampleResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/examples/{id}\x12e\n" +
	"\fListExamples\x12\x1c.example.ListExamplesRequest\x1a\x1d.example.ListExamplesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/examples\x12p\n" +
	"\rUpdateExample\x12\x1d.example.UpdateExampleRequest\x1a\x1e.example.UpdateExampleResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/examples/{id}\x12m\n" +
	"\rDeleteExample\x12\x1d.example.DeleteExampleRequest\x1a\x1e.example.DeleteExampleResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/examples/{id}B\x17Z\x15example-service/protob\x06proto3"

var (
	file_proto_example_proto_rawDescOnce sync.Once
	file_proto_example_proto_rawDescData []byte
)

func file_proto_example_proto_rawDescGZIP() []byte {
	file_proto_example_proto_rawDescOnce.Do(func() {
		file_proto_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_example_proto_rawDesc), len(file_proto_example_proto_rawDesc)))
	})
	return file_proto_example_proto_rawDescData
}

var file_proto_example_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_example_proto_goTypes = []any{
	(*CreateExampleRequest)(nil),  // 0: example.CreateExampleRequest
	(*CreateExampleResponse)(nil), // 1: example.CreateExampleResponse
	(*GetExampleRequest)(nil),     // 2: example.GetExampleRequest
	(*GetExampleResponse)(nil),    // 3: example.GetExampleResponse
	(*ListExamplesRequest)(nil),   // 4: example.ListExamplesRequest
	(*ListExamplesResponse)(nil),  // 5: example.ListExamplesResponse
	(*ExampleResponse)(nil),       // 6: example.ExampleResponse
	(*UpdateExampleRequest)(nil),  // 7: example.UpdateExampleRequest
	(*UpdateExampleResponse)(nil), // 8: example.UpdateExampleResponse
	(*DeleteExampleRequest)(nil),  // 9: example.DeleteExampleRequest
	(*DeleteExampleResponse)(nil), // 10: example.DeleteExampleResponse
}
var file_proto_example_proto_depIdxs = []int32{
	6,  // 0: example.ListExamplesResponse.examples:type_name -> example.ExampleResponse
	0,  // 1: example.ExampleService.CreateExample:input_type -> example.CreateExampleRequest
	2,  // 2: example.ExampleService.GetExample:input_type -> example.GetExampleRequest
	4,  // 3: example.ExampleService.ListExamples:input_type -> example.ListExamplesRequest
	7,  // 4: example.ExampleService.UpdateExample:input_type -> example.UpdateExampleRequest
	9,  // 5: example.ExampleService.DeleteExample:input_type -> example.DeleteExampleRequest
	1,  // 6: example.ExampleService.CreateExample:output_type -> example.CreateExampleResponse
	3,  // 7: example.ExampleService.GetExample:output_type -> example.GetExampleResponse
	5,  // 8: example.ExampleService.ListExamples:output_type -> example.ListExamplesResponse
	8,  // 9: example.ExampleService.UpdateExample:output_type -> example.UpdateExampleResponse
	10, // 10: example.ExampleService.DeleteExample:output_type -> example.DeleteExampleResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_example_proto_init() }
func file_proto_example_proto_init() {
	if File_proto_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_example_proto_rawDesc), len(file_proto_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_example_proto_goTypes,
		DependencyIndexes: file_proto_example_proto_depIdxs,
		MessageInfos:      file_proto_example_proto_msgTypes,
	}.Build()
	File_proto_example_proto = out.File
	file_proto_example_proto_goTypes = nil
	file_proto_example_proto_depIdxs = nil
}
